import { useTranslation } from 'next-i18next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { useRouter } from 'next/router';
import Image from 'next/image'
import Link from 'next/link';

import constants from '@sqill/utils/constants';

import Layout from '@sqill/components/layout';

import { Section, Wrapper, H1, H2, SquareDiv, ButtonWatch, StoreButtons, SportsDiv, Div, Ol, Li } from '@sqill/components/pages/home.styles';

const Home = () => {
  const { locale } = useRouter();
  const { t } = useTranslation('home');
  const meta = t('meta');

  return (
    <Layout {...meta}>
      <Section>
        <Wrapper>
          <H1>
            <Image src='/images/logo_white_gradient.svg' alt='sqill logo' width={390} height={130} />
            <span>{t('header.subtitle')}</span>
          </H1>
          <SquareDiv dangerouslySetInnerHTML={{__html: t('header.description')}} />
          <ButtonWatch>{t('header.watch')}</ButtonWatch>
          <H2>{t('header.download')}</H2>
          <StoreButtons>
            <Link href={constants.APP_STORE_URL}>
              <a><Image src={`/images/app_store_${locale}.svg`} alt='download app store' width={120} height={40} layout='fixed' /></a>
            </Link>
            <Link href={constants.PLAY_STORE_URL}>
              <a><Image src={`/images/google_play_${locale}.png`} alt='download play store' width={134} height={40} layout='fixed' /></a>
            </Link>
          </StoreButtons>
          <SportsDiv>
            <div>{t('header.available')}</div>
            <span><Image src='/images/icon_sports.png' alt='sqill logo' width={555} height={34} /></span>
            <div>{t('header.andSports')}</div>
          </SportsDiv>
        </Wrapper>
      </Section>
    </Layout>
  );
  // return (
  //   <div className={styles.container}>
  //     <Head>
  //       <title>Create Next App</title>
  //       <meta name="description" content="Generated by create next app" />
  //       <link rel="icon" href="/favicon.ico" />
  //     </Head>

  //     <main className={styles.main}>
  //       <h1 className={styles.title}>
  //         Welcome to <a href="https://nextjs.org">Next.js!</a>
  //       </h1>

  //       <p className={styles.description}>
  //         Get started by editing{' '}
  //         <code className={styles.code}>pages/index.js</code>
  //       </p>

  //       <div className={styles.grid}>
  //         <a href="https://nextjs.org/docs" className={styles.card}>
  //           <h2>Documentation &rarr;</h2>
  //           <p>Find in-depth information about Next.js features and API.</p>
  //         </a>

  //         <a href="https://nextjs.org/learn" className={styles.card}>
  //           <h2>Learn &rarr;</h2>
  //           <p>Learn about Next.js in an interactive course with quizzes!</p>
  //         </a>

  //         <a
  //           href="https://github.com/vercel/next.js/tree/canary/examples"
  //           className={styles.card}
  //         >
  //           <h2>Examples &rarr;</h2>
  //           <p>Discover and deploy boilerplate example Next.js projects.</p>
  //         </a>

  //         <a
  //           href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
  //           className={styles.card}
  //         >
  //           <h2>Deploy &rarr;</h2>
  //           <p>
  //             Instantly deploy your Next.js site to a public URL with Vercel.
  //           </p>
  //         </a>
  //       </div>
  //     </main>

  //     <footer className={styles.footer}>
  //       <a
  //         href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
  //         target="_blank"
  //         rel="noopener noreferrer"
  //       >
  //         Powered by{' '}
  //         <span className={styles.logo}>
  //           <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
  //         </span>
  //       </a>
  //     </footer>
  //   </div>
  // )
};

export const getStaticProps = async ({ locale }) => ({
  props: {
    ...await serverSideTranslations(locale, ['menu', 'footer', 'home']),
  },
});

export default Home;
